
/**
* BulbBrokenException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Lightbulb.idl
* Tuesday, May 15, 2018 9:28:48 AM CST
*/

public final class BulbBrokenException extends org.omg.CORBA.UserException
{

  public BulbBrokenException ()
  {
    super(BulbBrokenExceptionHelper.id());
  } // ctor


  public BulbBrokenException (String $reason)
  {
    super(BulbBrokenExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class BulbBrokenException
