
/**
* LightBulbOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Lightbulb.idl
* Tuesday, May 15, 2018 9:28:48 AM CST
*/

public interface LightBulbOperations 
{
  void on () throws BulbBrokenException;
  void off ();
  boolean isOn () throws BulbBrokenException;
} // interface LightBulbOperations
