
/**
* LightBulbHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Lightbulb.idl
* Tuesday, May 15, 2018 9:28:48 AM CST
*/

public final class LightBulbHolder implements org.omg.CORBA.portable.Streamable
{
  public LightBulb value = null;

  public LightBulbHolder ()
  {
  }

  public LightBulbHolder (LightBulb initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LightBulbHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LightBulbHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LightBulbHelper.type ();
  }

}
