
/**
* LightBulb.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Lightbulb.idl
* Tuesday, May 15, 2018 9:28:48 AM CST
*/

public interface LightBulb extends LightBulbOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LightBulb
